sudo: required
dist: trusty
os:
- osx
- linux
env:
  matrix:
  - NODE_ENV=dev
  - NODE_ENV=prod
  global:
    secure: Ec2Q23NsZg4KCvfUgXLVCbthQ9zflnR/tkinPh/49YxoBErTGCBCUMRPOfcNwSsewZywdxqMc70iLK4hQH8n3413VoC3dY2CKBxMNMCv2QG29+qUZ/QbBHzdkWHF1zg8WMz4iPksZm1gN8syQ0NU8NwM5uKI0KqyVOn6uJq45oJNd3lycz9WQYb96utyIweJ2lCugEfmtq0m/FdItYi44yuPIL8aHsGXNEpxVmcaa+efzQ2xVlvwgUTKLBgCtWX1q6ynzs/C8vV4+T1Eao5KI4qNaZpB/Oh0lu5lvJ+FVMDtP0KhmEWMmO6rQleFNujDFI6JXcTg2WZ/WEPfCjI9NaDGWut1yBxeGRURHOFBBC+YrIYfgvMHfA86XgI0ewBXNLp7TKME46NEAIvOh3wwWUWismPDrMaVO9DRIzFvN1ypfnzlpABLC99hXjIIKD5KKbvn5ltxmEJAJywI5MPazEjsFUGiqb2MoHyorHOWDOvL4dQGVUCUvgMuwmN6EA8r/ZlFsymYBcIWieUAm2JZNIfEX0SjM/KlWDtAKxCtK94ggHxZ6pxOwZLqN7PEssI8FOK8zNdmTwUVLSoz81TBIfoLctWXfea9BURDhktnRMvlJNVFodgK7kpaBU5/i9Zggxqg3LryRdgQX/2R/xog0NOZXRjv3Y3GX/4PSNt1w0k=
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
- yarn build
- yarn package
before_deploy:
- ls dist
- if [[ "$NODE_ENV" == "dev" ]]; then mv dist/$(ls dist) dist/mock-$(ls dist); fi
- export APP_PKG_DIR="$(ls dist)";
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OUTPUT_PATH=dist/$APP_PKG_DIR/safe-browser.crust.config;
  else export OUTPUT_PATH=dist/$APP_PKG_DIR/'SAFE Browser.app'/Contents/Resources/'SAFE
  Browser.crust.config'; fi
- echo $OUTPUT_PATH
- printenv
- echo $GITHUB_ACCESS_TOKEN
- if [[ "$NODE_ENV" == "prod" ]]; then TOKEN="$GITHUB_ACCESS_TOKEN" OWNER="MaidSafe" REPO="release_config"
  REPO_PATH="safe_authenticator/safe_browser.crust.config" FILE="https://api.github.com/repos/$OWNER/$REPO/contents/$REPO_PATH"
  curl --header "Authorization:token $TOKEN" --header "Accept:application/vnd.github.v3.raw"
  --output $OUTPUT_PATH $FILE; fi
- if [[ "$NODE_ENV" == "dev" ]] && [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then rm -f dist/$APP_PKG_DIR/'SAFE
  Browser.app'/Contents/Resources/'SAFE Browser.crust.config'; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp build/log.toml dist/$APP_PKG_DIR/;
  fi
- ls dist/$APP_PKG_DIR
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  cd dist && zip -r -q -y $APP_PKG_DIR.zip
  $APP_PKG_DIR && cd ..; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd dist && ditto -c -k --sequesterRsrc
  --keepParent $APP_PKG_DIR $APP_PKG_DIR.zip  && cd ..;  fi
- ls dist
- rm -rf dist/$APP_PKG_DIR
- ls dist
- export RELEASE_DIR="$(ls dist/*.zip)";
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sha256sum dist/*.zip >> dist/$APP_PKG_DIR.txt;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shasum -a 256 dist/*.zip >> dist/$APP_PKG_DIR.txt;
  fi
- ls dist
- export SHA_256_SUM="$(ls dist/*.txt)";
- echo "deploying ${RELEASE_DIR} to GitHub releases as tagged with ${TRAVIS_TAG}"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Ec2Q23NsZg4KCvfUgXLVCbthQ9zflnR/tkinPh/49YxoBErTGCBCUMRPOfcNwSsewZywdxqMc70iLK4hQH8n3413VoC3dY2CKBxMNMCv2QG29+qUZ/QbBHzdkWHF1zg8WMz4iPksZm1gN8syQ0NU8NwM5uKI0KqyVOn6uJq45oJNd3lycz9WQYb96utyIweJ2lCugEfmtq0m/FdItYi44yuPIL8aHsGXNEpxVmcaa+efzQ2xVlvwgUTKLBgCtWX1q6ynzs/C8vV4+T1Eao5KI4qNaZpB/Oh0lu5lvJ+FVMDtP0KhmEWMmO6rQleFNujDFI6JXcTg2WZ/WEPfCjI9NaDGWut1yBxeGRURHOFBBC+YrIYfgvMHfA86XgI0ewBXNLp7TKME46NEAIvOh3wwWUWismPDrMaVO9DRIzFvN1ypfnzlpABLC99hXjIIKD5KKbvn5ltxmEJAJywI5MPazEjsFUGiqb2MoHyorHOWDOvL4dQGVUCUvgMuwmN6EA8r/ZlFsymYBcIWieUAm2JZNIfEX0SjM/KlWDtAKxCtK94ggHxZ6pxOwZLqN7PEssI8FOK8zNdmTwUVLSoz81TBIfoLctWXfea9BURDhktnRMvlJNVFodgK7kpaBU5/i9Zggxqg3LryRdgQX/2R/xog0NOZXRjv3Y3GX/4PSNt1w0k=
  file:
  - "${RELEASE_DIR}"
  - "${SHA_256_SUM}"
  draft: true
  prerelease: true
  tag_name: "$TRAVIS_TAG"
  on:
    tags: true
